### ISSUE TITLE
Abgabe Präsentation

### ISSUE THREAD

**Issue by alexander-suter** [accefa/doku#114]

**Comment by alexander-suter** [comment]
Wir treffen uns am 28.01.2015 an der HSLU für die Erstellung der Präsentation.

**Comment by ninux** [comment]
Wann und wo genau? =)

**Comment by alexander-suter** [comment]
jetzt, ob der mensa

**Comment by ninux** [comment]
Ok super. Komme etwas verspätet (ca. 10:00 Uhr) wegen Bauinspektion ^^

**Comment by alexander-suter** [comment]
ok!
