### ISSUE TITLE
Präsentation mit LaTeX?

### ISSUE THREAD

**Issue by ninux** [accefa/doku#125]
#### Problem
Ich habe begonnen eine Präsentation mit LaTeX aufzusetzen (siehe branch *pres*). Dies ist so aber nicht abgesprochen.

#### Frage
Wollen wir diese LaTeX Präsentation benutzen?

##### Pro & Contra
| pro | contra |
|-----|--------|
| übliche LaTeX Vorteile | übliche LaTeX Nachteile |
| Schon einiges Vorbereitet | - |
| Arbeiten wie gewohnt über Git/GitHub/LaTeX | - |
| - | keine Animationen |

##### Falls ja
Dann werde ich diese so weit wie möglich erweitern bis zum gemeinsamen Termin und merge asap den branch mit master.

##### Falls nein
Ich breche mit der LaTeX Variante ab und jemand anders übernimmt die Implementierung mit alternativen Tools.

**Comment by alexander-suter** [comment]
weiter so - das ist tip top! danke!

ich kann heute oder morgen schon mal reviewen.

**Comment by ninux** [comment]
OK super! Vielen Dank noch für die schnelle Antwort!

**Comment by wuethrich44** [comment]
:+1:
