### ISSUE TITLE
Präsentation - ET Slides erstellen

### ISSUE THREAD

**Issue by ninux** [accefa/doku#127]
Slides erstellen für ET Bereich
- [x] Übersicht
- [x] Fachgruppe pren-et
- [x] Schrittmotor
- [x] Brushlessmotor
- [x] DC-Motor
- [x] Freedomboard
- [ ] Energieversorgung

**Comment by ninux** [comment]
Soll ich die Energieversorgung überhaupt in die Präsentation einbauen?

**Comment by alexander-suter** [comment]
Ich denke es ist schon genug drin - lass es doch aus. wir können es sonst morgen noch diskutieren.

**Comment by ninux** [comment]
Super! =)
