### ISSUE TITLE
Präsentation - Slides zum Projektmanagement erstellen

### ISSUE THREAD

**Issue by ninux** [accefa/doku#129]
Slides zum Projektmanagement erstellen
- [x] Mehtode vorstellen
- [x] Umsetzung aufzeigen
- [x] Regel- und Kontrollstrukturen darstellen
- [x] Projektverlauf aufzeigen
- [x] gource-output zeigen (als Zeitpuffer)

**Comment by ninux** [comment]
- [ ] Stimmen die Slides zum Projektmanagement?
- [ ] Umfang und Inhalt ok?
- [ ] Gource-Video als Zeitpuffer/Unterhaltungseffekt?

**Comment by alexander-suter** [comment]
Hoi Ervin

Der Umfang ist soweit in Ordnung. 

Meine Ideen / Anmerkungen:
- Projektmanagement am Schluss oder am Anfang der Präsentation?
- gource Parameter braucht es meiner Meinung nach in den Folien nicht.
- Generell ist gource ja nur eine Spielerei, welche aber doch noch witzig ist. Ich weiss momentan noch nicht wie man das in die Präsentation einbauen kann? Ich finde, dass wenn man es mitten in der Präsentation 1:24 min abspielt, dass das etwas merkwürdig ist, da es ja eigentlich nur eine Spielerei ist. Eventuell kann man den Anfang einfach damit beginnen - oder am Ende noch abspielen und schon in die Diskussion einleiten, während das noch läuft?

Das waren nur mal ein paar Gedanken von mir.

**Comment by ninux** [comment]
Vielen Dank! Die Besprechung von heute im Plenum schliesst dieses Issue definitiv =)
