### ISSUE TITLE
Antriebe/Netzteil

### ISSUE THREAD

**Issue by ninux** [accefa/doku#93]
Kurze Beschreibung der Motoren verfassen.
- [x] Schrittmotor
- [x] Brushlessmotor
- [x] Gleichstrommotor
- [x] Encoder/Drehzahlgeber

**Comment by alexander-suter** [comment]
Gemäss Adriano sind die Berechnungen gemacht. Ervin wird nun noch eine Anpassung an der Doku machen. Das ganze sollte dann bis Sonntag Abend abgeschlossen sein.

**Comment by ninux** [comment]
Ich habe den Abschnitt (Anhang G.3 Gleichstrommotor) nun angepasst und ergänzt. Darf ich dich bitten diesen kurz durchzulesen und ggf. das Isse zu schliessen wenn alles korrekt und verständlich ist. Vielen Dank =)

**Comment by alexander-suter** [comment]
Tip top
